name: CI

on:
  push:
    branches: ["master"]
    tags: ["juniper*@*"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  pull_request:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macOS
          - windows
        toolchain:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: clippy, rustfmt
      - name: Linting
        run: cargo clippy
      - name: Formatting
        run: cargo fmt
      - name: Tests
        run: cargo test
      - name: Check
        run: cargo check