name: CI

on:
  push:
    branches: ["master"]
    tags: ["juniper*@*"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  formatting_and_linting:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v3
      -   uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true
            components: clippy, rustfmt
      -   name: Linting
          run: cargo clippy
      -   name: Formatting
          run: cargo fmt --all -- --check
  pull_request:
    needs:
      - formatting_and_linting
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - macOS
          - windows
        toolchain:
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: clippy, rustfmt
      - name: Install mdbook
        run: cargo install mdbook
      - name: Tests
        run: cargo test -r --all-features
      - name: Test book
        run: mdbook test book -L target/release/deps
      - name: Check
        run: cargo check --all-features
